### ISSUE TITLE
git commit

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#10]
I finished the tutorial successfully but I am confused on what the git commit or anything to do with git actually does. I never used git before outside the git tutorial we did in class but I still don't understand what I am supposed to do with the git commit command? Is git commit how I save my work? I still have my nitrous window up just in case.

**Comment by beisert1** [comment]
i did:

"git add ."
then
"git commit"
then finally i did
"git push"

Is this the correct way?

**Comment by beisert1** [comment]
When I enter git push I was assuming it pushes my local files to the remote server but I dont think I am correct?When I use git push in the terminal I get the following error:

ERROR: Permission to gaslight/nku-rails.git denied to beisert1.  
fatal: Could not read from remote repository.                                                                                  

Please make sure you have the correct access rights  
and the repository exists.

**Comment by jaimerump** [comment]
On the Nitrous box you have a copy of the original nku-rails repository that you created with the clone command. That's the repository you're committing to, and the repository they're checking when they go to grade the assignment. So for this you just use "git add ." then "git commit" to commit to the copy on the Nitrous box. If you pushed your code back to the original github repo you cloned from, that would mess up everyone who started the assignment after you.

**Comment by Spartan-196** [comment]
@jaimerump is correct. There is no need to do a git push as your Nitrous.io box is its own git repository.

**Comment by beisert1** [comment]
Thanks everyone!
