### ISSUE TITLE
Adding comment not working anymore

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#11]
Adding comments used to work but now after I finished the tutorial everything works except for adding new comments. I triple checked the syntax and I believe it might of happened in the re-factoring section of the tutorial because I was able to add comments before that. Here is my error:

![image](https://f.cloud.github.com/assets/6433253/1992516/318edcec-84c1-11e3-9bed-7644d72b00e5.png)

**Comment by JesseeMeadows** [comment]
Seems in the directions, the code goes from:
"@comment = @post.comments.create(params[:comment].permit(:commenter, :body))"
to 
"@comment = @post.comments.create(params[:comment])"

When adding the "destroy". Not sure why but that's your problem.

**Comment by beisert1** [comment]
Thank you I changed it back to "@comment = @post.comments.create(params[:comment].permit(:commenter, :body))" and it works now!!!

Thanks again!
