### ISSUE TITLE
No Method error in welcome#index

### ISSUE THREAD

**Issue by Spartan-196** [launchscout/nku#12]
I have completed the tutorial all the way though check my syntax over a few times and cannot find what is giving me this no method error on my index page.

![noomethod](https://f.cloud.github.com/assets/1337533/1997085/b111b13a-851e-11e3-92d1-19ab4d3f7c9b.png)

I am going down through the tutorial again checking everything over, if any one has suggestions I'll take them.

**Comment by Sparkesg1** [comment]
The noMethod error I had was caused by having my def xyz below the "private" line.  Check that if you haven't under your controller.

**Comment by swiedaa1** [comment]
While you check that, make sure there isnt anything under the private identifier. The only thing that should under private is the line it told you to type with private. If you have other things there, it could cause some more trouble.

**Comment by mitchlloyd** [comment]
You're not setting up the `@posts` instance variable in your controller. As others mentioned, marking your controller method as private (under the `private` label) can cause this problem.

**Comment by Spartan-196** [comment]
Inside of my posts_controler.rb the only thing under private is 

```
  private
  def post_params
    params.require(:post).permit(:title, :text)
  end
```

as it is shown in 5.6
[from the getting started guide]

```
def create
  @post = Post.new(post_params)

  @post.save
  redirect_to @post
end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end
```

Is this to say that to correct this I should now remove the private line?

**Comment by Sparkesg1** [comment]
private
  def post_params
    params.require(:post).permit(:title, :text)
  end

Is the correct bit.

**Comment by Spartan-196** [comment]
My index.html.erb was in the wrong location :/ 
thanks @rockwood
