### ISSUE TITLE
ArgumentError in Posts#new.html.erb 

### ISSUE THREAD

**Issue by Sparkesg1** [launchscout/nku#13]
For the life of me I cannot figure out what is failing to be defined and causing this issue.  Any help would be awesome.

ArgumentError in Posts#new.html.erb

Showing /home/action/nku-rails/app/views/posts/_form.html.erb where line #1 raised:

First argument in form cannot contain nil or be empty

Extracted source (around line #1):

<%= form_for @post do |f| %>
<% if @post.errors.any? %>

<div id="error_explanation">
<h2><%= pluralize(@post.errors.count, "error") %> prohibited

_______________________________________________
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

---

class PostsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def new 
    @post = Post.new
  end
  def create
    @post = Post.new(params[:post].permit(:title, :text))
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  def show
    @post = Post.find(params[:id])
  end
  def index
    @post = Post.all
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])

```
if @post.update(params[:post].permit(:title, :text))
  redirect_to @post
else
  render 'edit'
end
```

  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

**Comment by rockwood** [comment]
It looks like your parameters aren't defined correctly. Take a look at this:

http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html
