### ISSUE TITLE
NoMethodError in PostsController#create

### ISSUE THREAD

**Issue by swiedaa1** [launchscout/nku#14]
So, I'm trying to add additional methods to make the Name, Nickname, Email, and Image URL fields. I've gone through all of my files to make sure where it used to just say  (:title, :text) have been edited to include title1, title2, title3, and text. I've edited the post controller, the edit, form, and show. I've gone through the directions several times and I finally have additional text boxes, I cant click the post button without receiving the error.

I wasnt trying to get the code perfect yet, please excuse the formatting for titles rather than calling them name, nickname, etc yet. I figured I could make things pretty once I got to the bottom of this darn error.

Page link: http://swiedaa1-72810.use1.nitrousbox.com/posts

![screenshot 2014-01-28 14 29 03](https://f.cloud.github.com/assets/6432799/2022803/94052c20-8852-11e3-9641-ed1b86604fdf.png)

**Comment by cdmwebs** [comment]
@swiedaa1 have you added those properties to your model?

**Comment by swiedaa1** [comment]
I was messing with title1 first to figure it out before the others since its still giving me an error. I do have it in my post.rb 
If I go through every .rb, .erb, and .html file and change them all back to just :title, it works. The problem is that I need to duplicate it or have more than :title and :text.

I may have completely missed what you just asked. I've been working on this since 7am, brain is a bit fried. 

![screenshot 2014-01-28 14 45 50](https://f.cloud.github.com/assets/6432799/2022990/dcacb824-8854-11e3-95f9-026723c93140.png)

**Comment by cdmwebs** [comment]
@swiedaa1 ok, no worries. The error message is saying that the `nickname` doesn't exist on a post. In order to add it, you'll have to create a database migration and add the field to the `posts` table. Does that make sense?

**Comment by swiedaa1** [comment]
It does. I'm a dingus. I realized I had "nickname" in one place. I changed it back to "title1" like it is everywhere else.

I did try to use the following line: rails generate model Post2 title1:string title2:string title2:string text:text but it didnt exactly do me any good.

**Comment by cdmwebs** [comment]
@swiedaa1 that's because your model already exists. You just want to add more properties (or fields) to it. In that case you'd just generate a migration and `add_column :posts, :nickname, :string` in the `change` method. That would add the `nickname` column to the `posts` table for you.

**Comment by swiedaa1** [comment]
Alright, That may be my issue. I've simply generated a whole new table. I'm not too certain on how to add to my table.

I believe that I've followed the suggestions you'v provided but i'm still receiving the same error.

**Comment by cdmwebs** [comment]
@swiedaa1 can you paste the contents of `db/schema.rb` in here?

**Comment by swiedaa1** [comment]
Perhaps we're not as far along in class as you're expecting, that or I am VERY lost.

Contents of db/schema.rb

/# encoding: UTF-8  
/# This file is auto-generated from the current state of the database. Instead  
/# of editing this file, please use the migrations feature of Active Record to  
/# incrementally modify your database, and then regenerate this schema definition.  
/#  
/# Note that this schema.rb definition is the authoritative source for your  
/# database schema. If you need to create the application database on another  
/# system, you should be using db:schema:load, not running all the migrations  
/# from scratch. The latter is a flawed and unsustainable approach (the more migrations  
/# you'll amass, the slower it'll run and the greater likelihood for issues).  
/#  
/# It's strongly recommended that you check this file into your version control system.                                                                                                                          

ActiveRecord::Schema.define(version: 20140128201150) do                                                                                                                                                             

"schema.rb" 42L, 1409C        

Sorry, had to add the / to keep the text form jumping off the page.

**Comment by cdmwebs** [comment]
@swiedaa1 cool. If you wrap all the code with backticks (`) it'll preserve the formatting in these comments. Check [this](https://help.github.com/articles/github-flavored-markdown#fenced-code-blocks) out for more info.

Back to your schema, is there more after the `ActiveRecord::Schema.define(version: 20140128201150) do` line?

**Comment by swiedaa1** [comment]
Either way, I'm fairly confused. If I change everything from nickname or title1 back to just title, it all works. Flawlessly. Well, as far as I have been able to code, anyway. Is there another directory I should be looking in?

And yeah, once again, I am a dingus. There is more.

```
ActiveRecord::Schema.define(version: 20140128201150) do                                                                                                                                                             

 create_table "comments", force: true do |t|                                                                                                                                                                       
   t.string   "commenter"                                                                                                                                                                                          
    t.text     "body"                                                                                                                                                                                               
    t.integer  "post_id"                                                                                                                                                                                            
    t.datetime "created_at"                                                                                                                                                                                         
    t.datetime "updated_at"                                                                                                                                                                                         
  end                                                                                                                                                                                                               

  add_index "comments", ["post_id"], name: "index_comments_on_post_id"                                                                                                                                            

  create_table "post2s", force: true do |t|                                                                                                                                                                         
    t.string   "name"                                                                                                                                                                                               
    t.string   "nickname"                                                                                                                                                                                           
    t.string   "email"                                                                                                                                                                                              
    t.string   "image"                                                                                                                                                                                              
    t.datetime "created_at"                                                                                                                                                                                         
    t.datetime "updated_at"                                                                                                                                                                                         
  end                                                                                                                                                                                                               

  create_table "posts", force: true do |t|                                                                                                                                                                          
    t.string   "title"                                                                                                                                                                                              
    t.text     "text"                                                                                                                                                                                               
    t.datetime "created_at"                                                                                                                                                                                         
    t.datetime "updated_at"                                                                                                                                                                                         
  end                                                                                                                                                                                                               

end
```

**Comment by cdmwebs** [comment]
Perfect! Ok, it looks like you accidentally named your model `Post2s`. Try this:
1. Destroy that bad one: `rails destroy model Post2s`.
2. Create a migration to add your new fields to `posts`: `rails generate migration add_fields_to_posts`
3. Edit the file it creates (probably something like `db/migrate/2014012816300000_add_fields_to_posts.rb`).
4. Make it look like this:

```
def change
  add_column :posts, :nickname, :string
  add_column :posts, :email, :string
  add_column :posts, :image, :string
end
```
1. Migrate your database: `rake db:migrate`.

Does it work now?

**Comment by swiedaa1** [comment]
You are seriously my new favorite person. Thank you! It works now!

**Comment by cdmwebs** [comment]
Nice work!
