### ISSUE TITLE
My "Post" can't retrieve the 'title'

### ISSUE THREAD

**Issue by camdixon** [launchscout/nku#16]
http://dixonc3-72812.use1.nitrousbox.com/posts/new

I'm receiving the error inside the view   show.html.erb
Any idea on what is wrong?

Showing /home/action/nku-rails/app/views/posts/show.html.erb where line #3 raised:

undefined method `title' for nil:NilClass

Extracted source (around line #3):  "@post.title"

<p
  <strong  Title:</strong>
  <%= @post.title 
</p>

<p
  <strong  Text:</strong>
  <%= @post.text 
</p

<p
<strong  Title:</strong>
<%= @post.title 
</p
<p

**Comment by alexkoepke** [comment]
What step are you on?—
Alex Koepke
(513) 236-7281

**Comment by jaimerump** [comment]
Notice the `undefined method for nil:NilClass`. That means that your post is undefined. Do you have an @ in front of the post variable in the controller? It might be something as simple as you forgetting to make the post available to the view. Or, if you have the show function defined under the private keyword, we found out that that causes all kinds of issues.

**Comment by camdixon** [comment]
+1 to you both!

Turned out it was the "private" keyword.
Figured it out after I tried all of your guys suggestions.
