### ISSUE TITLE
ActionController: Exception

### ISSUE THREAD

**Issue by staffordw1** [launchscout/nku#17]
I've just been powering through this assignment because I'm pretty sure I have no idea what I'm doing but some things seem to be working which is really surprising but I'll take what I can get and not complain. Anyways, my error seems to be this: 

![screen shot 2014-01-29 at 2 30 12 pm](https://f.cloud.github.com/assets/6433255/2033396/478965f8-891c-11e3-8091-ddf809a13b5c.png)

...hopefully that shows up as a picture.

I have the student list working, and was able to add students to it and have them appear on the list. But now I can't add students for some reason(I'm trying to navigate to the add students screen by just adding /new to the end of my URL since I can't figure out how to create a link to the page), and I'm not exactly sure why. Comparing this code to the tutorial code makes me feel as though it should work, the only difference is that I'm permitting 4 parameters instead of just the two.

Other than that, I'm not exactly sure how to make the link appear to add a new student on the index/student_list screen. The tutorial code didn't seem to have anything that was obviously the code for that, which is leaving me stumped... but I guess that's another issue entirely...

**Comment by jaimerump** [comment]
When does this error occur? I'm pretty sure the validation should be done in the create function, after you post the form, but it looks like it's trying to validate in the new function instead, when you navigate to the page to add a student.

Also, to add a link, you should just be able to do something like
`<%= link_to "{Link text}", {route_name}_path %>`, where route name is whatever name the rake command displayed for the particular route.

**Comment by Sparkesg1** [comment]
if the parameter student is the issue, could it be a pluralization issue you may have done?  The coding appears exactly as mine and currently mine is working fine from that particular location.  This is either a db misentry or similar is my guess.

**Comment by staffordw1** [comment]
@jaimerump the error occurs whenever I try to navigate to the url to add students. Where the form to enter the student information should appear.

@Sparkesg1 idk, if I change params.require(:student) to params.require(:students) I get the same error which seems pretty strange to me, but is that what you mean?

Also, adding the line of code <%= link_to "Create", new_student_path %> under my table in the index view did make the link appear and the link directs me straight to the same error page so that's a step forward :) thanks!

**Comment by jaimerump** [comment]
@staffordw1 Progress! That seems strange that it's using the params function when you're going to the new function instead of create. In the blog tutorial, we had to create a blank post in the new function, to be passed to the form:
`def new
    @post = Post.new
  end`
Could it be that you forgot to do that? I'm pretty sure that would show up as nil:NilClass in the form code instead of doing this, but it's worth checking. Also, you could try `permit!` instead, to tell it to permit whatever. That's pretty insecure, and I'm pretty sure your code is failing before that point, but it might enlighten us.

**Comment by mitchlloyd** [comment]
Yep, I think @jaimerump has it. You must be using `student_params` in your `new` action. When a user hits the new action, there aren't really any params to speak of. They just hit the page with a URL. When you update and create you want to be working with student_params.

**Comment by staffordw1** [comment]
Yeah, it looks like you guys are right, I was creating a new Student using Student.new(student_params) so it was failing there. I switched it to just "Student.new" and it seems to be working. It's not showing exactly what I want but the error is gone so I'll try to fix that myself and I'll let you guys know if I get stuck again. Thanks guys!
