### ISSUE TITLE
Can't connect to my Nitrous.IO box

### ISSUE THREAD

**Issue by finkecj** [launchscout/nku#20]
It will keep sitting there "connecting". Sometimes I also get a message saying "ssh: can't resolve user1.nitrousbox.com". I was able to connect before. Any thoughts?

**Comment by swiedaa1** [comment]
It seems to be down. I just get an error after it says "loading" forever.

**Comment by rockwood** [comment]
Sorry guys. It looks like Nitrous is down at the moment. Checkout http://status.nitrous.io/ for updates

**Comment by finkecj** [comment]
Nitrous.io is reporting all services operational, but now when I try to open my finkec2 box it came up "connection lost, reconnecting..." then sits.

**Comment by swiedaa1** [comment]
Mine just connected. Give it another go?

**Comment by finkecj** [comment]
Still nothing.

**Comment by rockwood** [comment]
According to http://status.nitrous.io/, everything should be back up. Let me know if it's not.

**Comment by ilitvak** [comment]
It says that nitrous.io is operational yet my box has trouble connecting.  I have not had this issue before... I hav e restarted nitrous, shut it down ,and restarted my computer.

**Comment by rockwood** [comment]
@ilitvak I think we removed all paid boxes after the semester. If you think it's an issue with Nitrous, you may want to submit a support ticket.
