### ISSUE TITLE
400 Bad Request?

### ISSUE THREAD

**Issue by finkecj** [launchscout/nku#26]
Hey guys,

Whenever I try to click the update or the submit button for a student profile, I get a 400 Bad request page telling me "The plain HTTP request was sent to HTTPS port. I'm not sure what's going on, because when I submit the forms my information saves, but my url changes from http://finkec2-72813.use1.nitrousbox.com:443/posts/ to http://finkec2-72813.use1.nitrousbox.com:443/posts/. Any ideas as to why?

**Comment by rockwood** [comment]
Is it possible that when you clicked the "Preview" drop-down in the IDE that you selected `Port 3000 (SSL)`? You'll want to select just `Port 3000`

**Comment by jaimerump** [comment]
The protocol is http://, but the port is :443. The browser is trying to send an http request to the https port, it's literally what the error message says. No idea how the protocol and port got mixed up like that though, since none of the preview options use port 443.

**Comment by finkecj** [comment]
Oh I am so dumb, that's probably what I did.......................................oops.

Thanks! I've been sitting here working on this thinking I've messed up something.

**Comment by rockwood** [comment]
Good deal!
