### ISSUE TITLE
the flash has no color?

### ISSUE THREAD

**Issue by w1ll1am23** [launchscout/nku#27]
I guess this isn't that big of a deal, but my flash messages don't have any color to them? I have tried success, error, and notice in Firefox and Chrome. 

Here is the code:
redirect_to students_path
    flash[:success] = "Added Student!"

I have also tried this:
redirect_to students_path, :flash => { :notice => 'Added Student!' }

Same thing happens I see the message but it has no color. Anyone know why? Thanks.

**Comment by jaimerump** [comment]
How are you displaying the flash on the page? I'm assuming you have some sort of html template for it, so you just need to add css to change the color.

**Comment by rockwood** [comment]
The easiest way to do it is with an inline style (although it's not the most sustainable solution)

On the flash message html element (in `layouts/application.html.erb`), you'll put a style attribute like this:

`<p style=”color: red”>Added Student!</p>`

We'll talk more about CSS in a future class.

**Comment by w1ll1am23** [comment]
From everything i was reading the flash messages defaults to a color without any interaction :error is red, :success is green, and :warning is yellowish. For example http://ruby.railstutorial.org/chapters/sign-up#sec-the_flash the example in this site shows the flash message being green yet all they did was add the flash code to the controller.

**Comment by mitchlloyd** [comment]
In the example you're looking at they are using [Twitter Bootstrap](http://getbootstrap.com/).  Checkout section 5.1.2 of the article you linked.

Kevin and I are also using Twitter Bootstrap when we work on the assignments. We can talk about how to use this in your project more in class if people are interested, but it is not required for the assignment.
