### ISSUE TITLE
Flash not working

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#28]
I am not sure how to create the flash message. I tried following the guide as best I can.

In my users_controller:

```
def create
  @user = User.new(user_params)
  @user.save
  flash[:notice] = "student was successfully created."
  redirect_to @user, notice: "student was successfully created."
end
```

and in my applications layout: application.html.erb

```
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
```

This does display a message when a student is created however, it is not in a alert message box it just displays this text at the bottom of the page.

![image](https://f.cloud.github.com/assets/6433253/2054349/f769f90e-8ab3-11e3-9f8b-ce7dcb9b37b9.png)

**Comment by rockwood** [comment]
That's how it's supposed to work. If you want it to display on the top of the page, you just need to push the `flash.each...` block above the call to `yield` in `application.html.erb`
