### ISSUE TITLE
"Password Can't Be Blank Error" When I'm attempting enter a password for a new user and clicking submit

### ISSUE THREAD

**Issue by hopscotchscooter** [launchscout/nku#31]
So when I'm attempting to sing up a new user, I'm getting a "password can't be blank error" when attempting to submit. I've racked my brain trying to figure this out and I can't. 
![image](https://f.cloud.github.com/assets/6218900/2060542/497fbff4-8c20-11e3-8faf-85d9a7219bf9.png)

I have `has_secure_password` in my model. I think I'm doing everything right, but obviously I'm not. Has anybody else run across this problem? Any tips would be appreciated.

**Comment by jaimerump** [comment]
Could you post the code for the form and the action that's processing it? It's kind of hard to debug without any code.

**Comment by hopscotchscooter** [comment]
Sure. The code below is for the form, new.html.erb

```
<h1>Sign Up</h1>

<%= form_for :entry, url: entries_path do |f| %>
   <% if @entry.errors.any? %>
   <div id="error_explanation">
     <h3><%= pluralize(@entry.errors.count, "error") %> found. Please fix before attempting to resubmit.</h3>
     <ul>
       <% @entry.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
   <% end %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </p>

    <p>
     <%= f.label :password %><br>
     <%= f.password_field :password %><br>
   </p>

    <p>
     <%= f.label :password_confirmation %><br>
     <%= f.password_field :password_confirmation %><br>
    </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', entries_path %>
```

And the method under my controller is here... 

```
def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entries_path, :notice => "Signed up!"
    else
      render 'new'
    end
  end
```

and it's using the private method `entry_params` which is here...

```
private
  def entry_params
    params.require(:entry).permit(:first_name, :last_name, :email_address, :password_digest)
  end
end
```

**Comment by jaimerump** [comment]
I think you need to permit :password and :password_confirmation. As far as I can tell, the translation from those to :password_digest is made when Rails goes to add the record to the database.

**Comment by cdmwebs** [comment]
@jaimerump has it correct. You'll see warnings in your `log/development.log` file about those.

**Comment by hopscotchscooter** [comment]
I thought about that. But the problem then is, I get an undefined error for "password_digest='", which is shown below...

![image](https://f.cloud.github.com/assets/6218900/2060790/6c6316a0-8c30-11e3-9443-2549cc879fe5.png)

**Comment by jaimerump** [comment]
@cdmwebs Thanks for recommending that log file, that fixed an issue I was having with the assignment.

I would guess that that's because you're using a new model entry, and I'm guessing it doesn't have `has_secure_password`.

**Comment by hopscotchscooter** [comment]
But I've got that in my entry model, which is below. 
`class Entry < ActiveRecord::Base
  validates_presence_of :password, :on => :create
  include Gravtastic
  gravtastic
  has_secure_password
end`

I've been struggling with it since yesterday and can't figure it out.

**Comment by jaimerump** [comment]
Is there maybe an issue with gravtastic preventing it from even getting to has_secure_password then?

**Comment by hopscotchscooter** [comment]
Nope. Still getting the "undefined method `password_digest` error.

**Comment by cdmwebs** [comment]
@hopscotchscooter have you added the `password_digest` attribute to the model?

**Comment by hopscotchscooter** [comment]
I did. But I just added it to the existing table as shown below. Is that okay to do? 

```
class CreateEntries < ActiveRecord::Migration
  def change
    create_table :entries do |t|
      t.string :first_name
      t.string :last_name
      t.string :email_address
      t.string :password_digest

      t.timestamps
    end
  end
end
```

Or, do I need to run a command to actually add it?

**Comment by cdmwebs** [comment]
You were really close. You need to run `rake db:migrate`.

**Comment by hopscotchscooter** [comment]
Thanks @cdmwebs  . But I've done that as well and still getting the same error. I even looked at my schema and it doesn't seem to have changed. (it's below)

```
ActiveRecord::Schema.define(version: 20140202152055) do

  create_table "entries", force: true do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.string   "email_address"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
```

**Comment by cdmwebs** [comment]
@hopscotchscooter ah, okay. Sounds like you've already run the create migration once. In that case, you'll need to generate a new migration to add this field to the existing table. Try this:

`rails g migration add_password_digest_to_entries`

Then edit the newly created file and add `add_column :entries, :password_digest, :string` inside the empty `change` method.

And migrate again: `rake db:migrate`.

**Comment by hopscotchscooter** [comment]
You are awesome @cdmwebs . That fixed it. Thank you as well @jaimerump . Quick question before I close the issue though. So if you ever want to add more fields like we just created, you have to generate a new migration with the items, add them to the change method in the new file, and do a `rake db:migrate`. Why does that feel like a lot of work to get that done? Or was this just unique to this situation?

**Comment by cdmwebs** [comment]
@hopscotchscooter yep, that's the workflow. It seems like a lot here because you're the only person using the application right now. Think ahead to when you've deployed this to production and people are using the system. You continue developing locally, adding new features and attributes. When we're you're ready to deploy, you push your code and run those migrations which brings your production database current.

**Comment by hopscotchscooter** [comment]
@cdmwebs That certainly makes sense thinking about it that way. Thanks again for your help!

**Comment by cdmwebs** [comment]
@hopscotchscooter there's an alternative workflow you can use, but only if you haven't pushed your code anywhere else. What you _could_ do is undo the previous migration (in this case, you'd run `rake db:migrate:down VERSION= 20140202152055`), fix the migration (add your `password_digest` field to the table), then migrate again (`rake db:migrate`).

However, you'd drop your current entries table, which would be terrible in production and maybe even in development. That's why migrations are so awesome.

**Comment by jaimerump** [comment]
It feels like a lot of work to add columns that way, but it's a lot more work to add them with the SQL queries.

**Comment by cdmwebs** [comment]
@jaimerump ActiveRecord generates the SQL for us. So if you're using SQLite for development and PostgreSQL in production, the same migration will alter the tables correctly.
