### ISSUE TITLE
Password confirmation can't be blank error

### ISSUE THREAD

**Issue by swiedaa1** [launchscout/nku#32]
So, I tried following the direction from the identical closed post, but my problem seems to be different somewhere....

I will attach code in comments. 

![screenshot 2014-02-05 14 58 26](https://f.cloud.github.com/assets/6432799/2091493/0a6455d2-8ea0-11e3-8e97-e11defa9cc8f.png)

**Comment by swiedaa1** [comment]
User.rb 
class User < ActiveRecord::Base
validates :name, presence: true,  
                    length: { minimum: 2 } 
validates :nickname, presence: true,  
                    length: { minimum: 2 } 
has_secure_password
end

**Comment by swiedaa1** [comment]
Screen shotting is easier :)

![screenshot 2014-02-05 15 02 04](https://f.cloud.github.com/assets/6432799/2091562/aa1cb916-8ea0-11e3-83c3-b9b34d368de3.png)
![screenshot 2014-02-05 15 02 14](https://f.cloud.github.com/assets/6432799/2091563/aa23957e-8ea0-11e3-98fc-1db94c2f146c.png)
![screenshot 2014-02-05 15 02 28](https://f.cloud.github.com/assets/6432799/2091564/aa269ea4-8ea0-11e3-8e1c-1614540d6923.png)
![screenshot 2014-02-05 15 03 37](https://f.cloud.github.com/assets/6432799/2091565/aa29c444-8ea0-11e3-9cc6-e6a4f4842e7b.png)

**Comment by swiedaa1** [comment]
If it matters at all,this may help.
When I view the source code, it doesnt have a value...but everything else does?
![screenshot 2014-02-05 15 11 51](https://f.cloud.github.com/assets/6432799/2091663/d75a2e8a-8ea1-11e3-8c72-760fd0709a87.png)

**Comment by C-Khalid** [comment]
I don't think you need to permit password_digest

**Comment by swiedaa1** [comment]
I took it out just to see, same error :(

**Comment by cdmwebs** [comment]
What's `passcon`? Rails is going to look for a field called `password_confirmation`.

http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html

**Comment by swiedaa1** [comment]
I kind of thought that was a general naming scheme. Guess I'll go mess with it! I shall return shortly!

**Comment by swiedaa1** [comment]
Ok, so, I've changed everything to password_confirmation and now its saying password_confirmation cant be left blank. At least its a new error.
"Password confirmation can't be blank"

Should I be modifying this part for my purposes? Or is this just an example. 

```
user = User.new(name: 'david', password: '', password_confirmation: 'nomatch')
user.save                                                     
user.password = 'mUc3m00RsqyRe'
user.save                                                      
user.password_confirmation = 'mUc3m00RsqyRe'
user.save                                                      
user.authenticate('notright')                                   
user.authenticate('mUc3m00RsqyRe')                              
User.find_by(name: 'david').try(:authenticate, 'notright')      
User.find_by(name: 'david').try(:authenticate, 'mUc3m00RsqyRe') 
```

**Comment by cdmwebs** [comment]
@swiedaa1 nope, nothing to do there. Can you post your form's source code again?

Also, you don't need to store the `password` and `password_confirmation` in the database. That's a bad idea. The only field your table will need is the `password_digest`.

**Comment by swiedaa1** [comment]
Sure!
Uh...for some reason its a div? I dont even know whats happening anymore.
To drop from my table do I use the standard drop command or do I just delete that field from my schema? I'll still need password and password_confirmation in my parameters though, right?

![screenshot 2014-02-05 15 35 56](https://f.cloud.github.com/assets/6432799/2091895/37f21570-8ea5-11e3-9a68-1635bdb17f83.png)

**Comment by cdmwebs** [comment]
@swiedaa1 it's a `div` because it's wrapped for the error class. That's okay.

To drop, generate a migration and

```
def change
  remove_column :users, :password
  remove_column :users, :password_confirmation
end
```

Then run `rake db:migrate`.

**Comment by swiedaa1** [comment]
Ok, so, I've killed those fields and my form still works to the same extent. 
"Password confirmation can't be blank"

If you'd like to see this, it may help?
http://swiedaa1-72810.use1.nitrousbox.com/users/new

**Comment by swiedaa1** [comment]
Here is my repository if there is anything specifically that you need to see and I am not understanding.
https://github.com/swiedaa1/nku-rails

**Comment by cdmwebs** [comment]
@swiedaa1 I think this is it:

https://github.com/swiedaa1/nku-rails/commit/ed260d1ae1b5b9db9e327cb1cfbc0ac37d2f54f7#diff-4e05ad0d64e6100656b63ad1e78f32c5R49

**Comment by swiedaa1** [comment]
FOR THE LOVE OF EVERYTHING.
THANK YOU.

**Comment by cdmwebs** [comment]
![](http://blog.luisdaniel.com/wp-content/uploads/2014/01/26.gif)

**Comment by ghost** [comment]
I just fixed my problem because of this thread. "than q"
