### ISSUE TITLE
issue with Index

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#34]
So, I am trying to add authentication but running into an issue where I can't see the index page without being prompted for authentication.  I added this to my student model:

```
has_secure_password
```

and this to my controller:

```
http_basic_authenticate_with name: "student", password: "password", except[:index]
```

Shouldn't the except keep me from being prompted?

**Comment by jaimerump** [comment]
You don't want to use http_basic_authenticate for this. has_secure_password already provides you an authentication system.

**Comment by mitchlloyd** [comment]
You should remove the `http_basic_authenticate_with` from your app.  That is a totally different authentication scheme.

**Comment by awh112** [comment]
I was following an example using a 'user' instead of a 'student', but that change didn't do anything.  If I remove the 'except' portion, I am prompted, but if I leave it in, I get this:

![image](https://f.cloud.github.com/assets/6433265/2093047/9d86555a-8eb3-11e3-83b3-822421018ed3.png)

**Comment by awh112** [comment]
Ok, that makes sense.  Now, do we need to update the student model to have a password_digest, or to actually store the password and password confirmation?  I added the like to the model and ran `rake db:migrate`.  What am I missing?  As of now, students just don't save.

**Comment by jaimerump** [comment]
Yeah, you have to store the password_digest in the database. You don't need to store password and password_confirmation, has_secure_password automatically converts between those and password_digest for you.

**Comment by awh112** [comment]
Cool.  Now, I am keeping up with questions (don't know if I should be creating a new issue for each one).  As it stands now, if my password fields don't match, the model doesn't save, although I still get the toast that tells me it has.  If they do match, it works just fine.  Am I missing something?  I added some code that looks like this:

```
<%= form_for :student, url: students_path do |s| %>
  <% if @student.errors.any? %>
    <div class="error_messages has_error">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @student.errors.full_messages %>
          <li><%= message %>
        <% end %>
      </ul>
    </div>
   <% end %>
```

**Comment by C-Khalid** [comment]
Do you have an else statement when you try to save the model?

**Comment by awh112** [comment]
I do now, yes.  Now I have moved on and I am to the point where I have created the form for the login page, with the session controller and all that, but I can't find the student.  I am trying to do this:

```
def create
    student = Student.find_by_email(params[:email])
    flash[:info] = student.nane
    if student && student.authenticate(params[:password])
      session[:user_id] = student.id
      redirect_to root_url
    else
      flash[:error] = "Invalid username or password"
      render "new"
    end
  end
```

And here is the error I get:

![image](https://f.cloud.github.com/assets/6433265/2094182/7185ee30-8ec6-11e3-9999-dd4839badbd6.png)

Any ideas?

**Comment by awh112** [comment]
If I hardcode the email in the backend, I at least get the right user:

![image](https://f.cloud.github.com/assets/6433265/2094195/d2cd2e38-8ec6-11e3-97a7-c2a5e3a412c1.png)

So then, why does using params[:email] not work?  Using student.email doesn't work either.  Is something wrong with my student.authenticate?

**Comment by rockwood** [comment]
What does your sessions/new form look like? 

It seems like you're not posting `email`

**Comment by awh112** [comment]
I'm not sure I follow "what it looks like".  If I navigate there, I am sent to the same place, and my routes.rb looks like this:

```
 resources :students
  resources :sessions

  root to: 'welcome#index'

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
```

**Comment by jaimerump** [comment]
He means we need to see the code for the form. I had something like `form_for :student` in mine, and I was having trouble with it because I had to access everything like `params[:student][:email]` instead of just `params[:email]`. You might be having the same issue.

**Comment by awh112** [comment]
here is my new.html.erb for the session:

```
% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<h1>Log in</h1>

<%= form_tag sessions_path do %>
<p>
  <%= label_tag :name %>
  <%= text_field_tag :name, params[:name] %>
</p>

<p>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
</p>

<div><%= submit_tag "Log in" %></div>
<% end %>
```

**Comment by awh112** [comment]
So, if I do this, it works:

```
student = Student.find_by_email("howarda8@nku.edu")
    #flash[:info] = student.name
    if student && student.authenticate(params[:password])
      session[:user_id] = student.id
      redirect_to students_path
```

If params[:email] doesn't work, shouldn't params[:password] also not work?

**Comment by awh112** [comment]
Ah, I think I found it.  So, in my view I had this:

```
<%= label_tag :name %>
  <%= text_field_tag :name, params[:name] %>
```

when I needed this:

```
<%= label_tag :email %>
  <%= text_field_tag :email, params[:email] %>
```
