### ISSUE TITLE
Displaying proper username for signed in user

### ISSUE THREAD

**Issue by swiedaa1** [launchscout/nku#35]
Needless to say, I'm impressed to have made it this far.
Anyway, I cant for the life of me figure out how to display the name of the signed in user. The most I could get it to do was display what I assume is the session number. 

Please ask for more information because I honestly have no idea what code to paste. 

repo: https://github.com/swiedaa1/nku-rails

**Comment by jaimerump** [comment]
For starters, in which file are you outputting the session number?

**Comment by swiedaa1** [comment]
That a good question. I have to figure out what that code was. It USED to be in my index file but is no longer there.

It should be in the index.html.erb file under this:
`<% else %>
  Hello, <%= current_user[:user_id] %>!
<% end %></p>`

**Comment by swiedaa1** [comment]
I tracked through all of my commits and everything and I cant locate what I had it to when it was outputting the session id. It said something like <User 9823847z7294a92> which was pretty promising haha

**Comment by awh112** [comment]
I was able to get access to the currently logged in user by making some changes to the application_controller.  Ater that, you can just access the user by using `Student.find(session[:user_id]` (Student is the name of my model).  

You can also use the Student.find_by_email method, assuming that you have an email property defined off the Student model (or whatever your model is named).  Then you could just access the currently logged in user after checking that it isn't null and the properties match.

**Comment by mitchlloyd** [comment]
I see that you defined a helper method in your `ApplicationController` called current_user.  This method will give you access to the current user in your controllers and in your views. So in a view you can do something like:

```
<%= current_user.name %>
```

**Comment by swiedaa1** [comment]
I went through and commented on some of your comments in my repo, Mitchlloyd. Thank you for the help! 
Thank you awh112 as well! I actually wouldnt have been able to make it this far without the help of your "issues" thread! Your advice and suggestions have been wonderful.
