### ISSUE TITLE
Issue with parameters

### ISSUE THREAD

**Issue by camdixon** [launchscout/nku#36]
![selection_005](https://f.cloud.github.com/assets/4430359/2102486/6a1beebc-8f5f-11e3-9a8b-ae395609109b.png)

I don't understand why it would say this.  Inside my view that it is referencing I have this code:  

<h1>New User</h1>
 

<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

**Comment by awh112** [comment]
So is is actually showing your code on the web page?  It looks like you need to close the logic for the program code there, and then add your markup after that.  Have you tried having your markup outside an `<% end %>` tag?
