### ISSUE TITLE
Route issue, except I'm using the users_path

### ISSUE THREAD

**Issue by camdixon** [launchscout/nku#37]
![selection_006](https://f.cloud.github.com/assets/4430359/2103603/04793cb2-8f6f-11e3-99de-d91bbd054107.png)

I get this above routing error after I click "create new user" and submit the form.  Does anyone have any ideas?  Below is my routes.rb file and my controller.  I tried checking the "users_path" and found once case of "user_path" but I fixed it to the plural already and I still get the error.
## Routes.rb

RailsNku2::Application.routes.draw do
  get "welcome/index"
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  #resources :posts do
  #  resources :comments
  #end
  resources :sessions
  resources :users

  root 'welcome#index'

end
## Users Controller

class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, notice: "Successfully created #{@user.name}"
    else
      render "new"
    end
  end

  def index
    @users = User.all
  end

  def user_params
    params.require(:user).permit(:email, :password, :name, :nickname, :image)
  end

end

**Comment by mitchlloyd** [comment]
The problem is probably in your form. When you click the submit button in the form it is POSTing to "/users/new" when it should be posting to "/users".  Check the top of your form template. It should be something like: 

```
<%= form_for @user do |f| %>
```

**Comment by camdixon** [comment]
![selection_007](https://f.cloud.github.com/assets/4430359/2103908/b428cc96-8f73-11e3-8ec7-ddda8b76866f.png)

When i do that and then put it in code like [below] the above picture is the error I get, so I'm confused on how to proceed.

<h1>New User</h1>
 

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_area :password %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_area :nickname %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>

**Comment by mitchlloyd** [comment]
Ok, so now the error is saying that the method `name` isn't defined on your `User` model.  Looking in your `schema.rb` file, do you have a `name` property on your `users` table?

**Comment by camdixon** [comment]
No, I do not.  How do I add one?

Here is what I have in schema.rb : 
ActiveRecord::Schema.define(version: 20140206175013) do

  create_table "users", force: true do |t|
    t.string   "email"
    t.string   "password_digest"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end

**Comment by mitchlloyd** [comment]
Look into add_column or change_table in the rails migrations guide.

**Comment by camdixon** [comment]
Thanks that has fixed it.  :D
