### ISSUE TITLE
Sign in on sign up?

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#39]
So, everything is working fine, but when I sign up, I'm not sure how to approach creating a session after that form is completed.  Any ideas?

**Comment by jaimerump** [comment]
Capture the new user in a variable, then do something like `session[:user_id] = @new_user.id`?

**Comment by awh112** [comment]
Ok, but if I am doing that in the controller for the student, do I even have access to the session?

```
def create
    @student = Student.new(student_params)

    require 'digest/md5'
    email_address = @student.email.downcase    
    hash = Digest::MD5.hexdigest(email_address)

    @student.image = 'http://www.gravatar.com/avatar/' + hash    
    @student.save

    if @student.save
      redirect_to students_path, :notice => "You have successfully signed up."
    else
      render "new"
    end
  end
```

**Comment by awh112** [comment]
Ah, of course I do.  You were right, all I had to do was this: `session[:user_id] = @student.id`.

Thanks @jaimerump!

**Comment by jaimerump** [comment]
You should have access to everywhere. All of your ruby code runs on the server, and the session lives on the server, so as long as you're in the ruby code you should be able to access the session.
