### ISSUE TITLE
issue with deleting a user?

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#40]
Whenever I try to delete a user, the application_controller complains it can't find my user.  Is it because I am deleting them, and if so, how do I mitigate that?

**Comment by awh112** [comment]
Maybe I should type out the issue, wait 5 minutes, and if it hasn't been resolved by then, then create it.

I just had to set the current_user and session id's to nil.

**Comment by jaimerump** [comment]
I find that that works well. Same with StackOverflow, start writing the question, do a couple tests to articulate the problem properly and collect data, figure out the issue, and never end up actually submitting the question.
