### ISSUE TITLE
Routes issue here

### ISSUE THREAD

**Issue by finkecj** [launchscout/nku#42]
Hey guys, 

I'm running into a problem when I moved the app over to a new controller. It is now a "student_controller", but when I go to http://finkec2-72813.use1.nitrousbox.com/student/new I get the following error:

![capture2](https://f.cloud.github.com/assets/6433197/2110534/a099467e-9004-11e3-9f6c-507801bc0221.JPG)

I'm not sure how to add it but I do know the problem is students_path doesn't exist according to rake routes:

![capture](https://f.cloud.github.com/assets/6433197/2110537/c217caa0-9004-11e3-9e43-a07ffa511a2f.JPG)

Any ideas what I've done wrong?

**Comment by finkecj** [comment]
I did find that my schema was named "students" not "student" so I'm not sure if that is a problem with it or not.
![schema](https://f.cloud.github.com/assets/6433197/2110557/2917cb9c-9005-11e3-9ef1-086a4f7c1c5b.JPG)

**Comment by hopscotchscooter** [comment]
The table automatically generates the "s" on the end of student for the table. Have you tried `<%= form_for new_student_path(@student) do |f| %>` ?

**Comment by rockwood** [comment]
You probably want a `StudentsController` instead of `StudentController`. Then in your routes, you'll say `resources :students`

**Comment by finkecj** [comment]
Doing the `new_student_path(@student)` seems to have cleared it up. Would I have to re-create _everything_ to make a `StudentsController`?

**Comment by rockwood** [comment]
You can just rename the controller and it's file. You shouldn't need to change anything in the database.

For the majority of cases, controllers should be plural.

**Comment by finkecj** [comment]
Awesome. I've got it working (for the most part!)
