### ISSUE TITLE
Updating student models

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#43]
So, I found out that I can solve some issues by defining methods off of the model, so Student.rb, but now I am getting weird errors like this:

![image](https://f.cloud.github.com/assets/6433265/2115541/d725f554-9052-11e3-96f6-8840d55fb7ab.png)

Anyone else have the same issue?

**Comment by jaimerump** [comment]
I think the biggest part of your issue there is that `nil:NilClass`. One of your variables is undefined for some reason. It looks like students is undefined.

**Comment by awh112** [comment]
Is there really anything I can do to change that, though?  If we are running the tests written for us in class, assuming we shouldn't change them, is that an issue with the test or the model/controller?

**Comment by jaimerump** [comment]
The first `students` is defined with `students = Student.in_seat(1, now)`. I would assume that if you have in_seat defined, it isn't returning anything. Same with the second one and absent.

**Comment by mitchlloyd** [comment]
@jaimerump is right again. This test error is saying that `students` in the test is nil, instead of a collection of students.  Student.in_seat(1, now) is returning nil.

**Comment by mitchlloyd** [comment]
@awh112 Overall it sounds like the issue you're running into is an expected step in the TDD process. If you define Student.in_seat to return something other than nil, you should be able to move forward.
