### ISSUE TITLE
Need to recover

### ISSUE THREAD

**Issue by Sparkesg1** [launchscout/nku#44]
So, I wanted to try to play around with bootstrap and I apparently caused a horrible horrible destruction of well everything on nitrous.  I had (for once) intelligently pushed to github prior.  So, I have tried to clone off github off my account to no avail.  Suggestions?

**Comment by mitchlloyd** [comment]
You somehow totally hosed your config/application.rb file and overrode it with some weird YAML stuff. I reset that file by doing:

```
git checkout config/application.rb
```

You also had included some "Turbolinks" stuff in your application.js file, which is something that isn't installed. I reset that file by doing

```
git checkout app/assets/javasripts/application.js
```

You can pull individual files back by doing checkouts like that from the last commit. A more nuclear option is to use:

```
git reset --hard
```

Which will reset to your last committed state. Right now it seems to be working.

**Comment by Sparkesg1** [comment]
ty... I won't mess with that option again without much more research into what it is i'm messing with.

**Comment by Spartan-196** [comment]
This is good info, i needed to revert a file earlier too but they were minor changes so i undid them manually. 
Lets be honest though that gut wrenching panic feeling after you completely break your apps just before they are due is half the fun in this kind of class
