### ISSUE TITLE
create new user doesn't auto sign in

### ISSUE THREAD

**Issue by alexkoepke** [launchscout/nku#45]
Currently you when you create an account the user is directed to the log in page. What I would like it to do is auto log the user in after creating the account w/out directing the user to the log in screen. Any tips would be nice.

My server is currently running at the following URL
http://koepkea1-72836.use1.nitrousbox.com/users

You can find my code at the following URL
https://github.com/alexkoepke/nku-rails

**Comment by jaimerump** [comment]
When you create the new account, you could capture it in a variable, then set `session[:user_id]` or whatever you're using to track the current user to the newly created user's id.

**Comment by mitchlloyd** [comment]
@jaimerump is correct here. Having your ID set in the session is what ultimately determines whether you are logged in. @alexkoepke could you close this one down unless you have other questions about this?
