### ISSUE TITLE
TypeError in Students#index  no implicit conversion of nil into String

### ISSUE THREAD

**Issue by hurtta1** [launchscout/nku#47]
I've tried tweaking every file I could think of, I'm not really sure what the problem is, Any help would be appreciated.

no implicit conversion of nil into String
Extracted source (around line #14): #Name: 'student.Name

```
 <tr>
   <td><br/>
      <%= image_tag gravitar_url(student), :size => "48x48" %><br/>
      <%= 'Name: '+student.Name %><br/>
      <%= 'Nickname: '+student.Nickname %><br/>
      <%= 'Email: '+student.Email %><br/>
   <%= link_to 'Edit', edit_student_path(student) %>
```

**Comment by Spartan-196** [comment]
I see where you are trying to conjoin the value store in student.Name  to that of Name: to make 

```
Name: Student
```

in your code you can also do this with 

```
 <td><br/>
      <%= image_tag gravitar_url(student), :size => "48x48" %><br/>
      Name: <%= student.Name %><br/>
      Nickname: <%= student.Nickname %><br/>
      Email: <%= student.Email %><br/>
   <%= link_to 'Edit', edit_student_path(student) %>
```

if you want to get fancy you make your email a mailto: link with 

```
Email: <%= mail_to student.Email %>
```

**Comment by hurtta1** [comment]
Thanks! That part works now.
