### ISSUE TITLE
NoMethodError in SessionsController#create undefined method `find_by_email'

### ISSUE THREAD

**Issue by hurtta1** [launchscout/nku#48]
Now i'm stuck on this. 
  def create
    student = Student.find_by_email(params[:email])
    if student && student.authenticate(params[:password])
      session[:student_id] = student.id
      redirect_to show_student_path, :notice => "Welcome to your profile"

**Comment by jaimerump** [comment]
I noticed that in your database migrations you have name, nickname, email, and gravatar all starting with capital letters, perhaps that's the issue. I have mine named identically, except all lowercase, and find_by_email works fine for me.

**Comment by hurtta1** [comment]
I thought I tried that already,I'll give it another shot.

**Comment by hurtta1** [comment]
Guess I missed changing something, that ended up solving that problem, thanks!
