### ISSUE TITLE
Unable to make new users

### ISSUE THREAD

**Issue by Spartan-196** [launchscout/nku#49]
I think I missed a step in my migrates and making passwords and so fourth because when I try to make a user I get a lovely undefined password_digest message 
all changes have been commited to my github.

Students page is here (http://atkinsonj3-72805.use1.nitrousbox.com/students) if you want to see it yourself 

but it looks kind of like this 
![password_digest](https://f.cloud.github.com/assets/1337533/2116418/53666a08-9081-11e3-9018-b1fad3bab28b.jpg)

**Comment by jaimerump** [comment]
That's because in your students table in the database you need a column called password_digest. `Has_secure_password` automatically takes the password field from the form, and password_confirmation if you're setting the password, and generates the password_digest for you.

**Comment by Sparkesg1** [comment]
On top of super jaime being correct again, you won't be able to call (student_params) as it is defined under private.

**Comment by mitchlloyd** [comment]
Just for the record, I'm not seeing any issue with `student_params` in your controller. Defining it as a private method is the right thing to do here because you are only calling it from within the controller.

**Comment by Spartan-196** [comment]
Thanks @mitchlloyd I had intended to leave it in a private class as I don't want it callable by anything else

**Comment by Spartan-196** [comment]
It seems I had everything in place aside from in the database itself. I ended up dumping the db and remaking it  then migrating everything. I am now able to add users and log users in.
