### ISSUE TITLE
Tutorial - 5.2: The First Form

### ISSUE THREAD

**Issue by MatthewMcElwain** [launchscout/nku#5]
I keep getting an error which happens only after I add "url: posts_path" to new.html.erb

![capture](https://f.cloud.github.com/assets/6433263/1968124/c5721cde-82dd-11e3-845b-0f52aab35714.JPG)

**Comment by cdmwebs** [comment]
Hey @MatthewMcElwain, what's in your `config/routes.rb` file?

**Comment by MatthewMcElwain** [comment]
I accidentally reposted the problem, I got it working from the other thread but thanks anyway.
