### ISSUE TITLE
How to initialize variable for link_to

### ISSUE THREAD

**Issue by nemesis51** [launchscout/nku#50]
![error](https://f.cloud.github.com/assets/6432186/2118151/ce95a9ea-90f5-11e3-8942-0c7a74886275.png)

I have a login.html.erb in the views/students folder not sure why it works for 'new' and not the 'login'.

I also defined the login method in the controller but didn't help. so I am missing something still.

**Comment by C-Khalid** [comment]
try to add this line to the route file
get 'login', to: 'sessions#create', as: :login
and in the index
<%= link_to "login", login_path %>

**Comment by jaimerump** [comment]
@mekdif has it, you don't have a route defined. You can't use the path helper without a route defined.

**Comment by mitchlloyd** [comment]
@nemesis51 Are you still working on this issue? If not could you close this one down?
