### ISSUE TITLE
ActiveRecord::RecordNotFound in StudentsController#edit Couldn't find Student with id=1

### ISSUE THREAD

**Issue by hurtta1** [launchscout/nku#51]
My logout doesn't actually destroy the current session, just redirects to the login page.  Also when I have created multiple students, when I hit edit on any other students other than the first one it gives me the above error.  I'm pretty much at a loss..

this is what I have in my student_index

  <tr>
    <th><%= link_to 'Sign In', sessions_path %><br/><%= link_to 'New Student', new_student_path %><br/><%= link_to 'Back to Bueller Home', bueller_index_path %><br/>
      <%= link_to 'Back to CSC Projects Home', welcome_index_path %><br/><%= link_to 'Logout', sessions_path%> <p><p/></th>
    <th></th>
    <th></th>
  </tr>

this what I have in my sessions controller

  def create
    student = Student.find_by_email(params[:email])
    if student && student.authenticate(params[:password])
      session[:student_id] = student.id
      redirect_to students_path, :notice => "Log in successful!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:student_id] = nil
  redirect_to bueller_index_path, :notice => "logged out"
end

and my update in student_controller

  def update
    @student = Student.find(params[:id])
    #return false unless @student == current_student
    if @student.update(params[:student].permit(:name, :nickname, :email, :gravitar, :password, :password_confirmation))
      redirect_to students_path, :flash => {:notice => 'You have succesfully updated your account'}
    else
      render 'edit'
    end
  end

**Comment by Sparkesg1** [comment]
It appears you didn't call your variable from sessions_path, so it took the first option instead.  sessions_path(session) would fix it if I'm thinking it through correctly.

**Comment by mitchlloyd** [comment]
Your logout link just goes to sessions_path which is the sessions index. Seems like you would want that link to hit your sessions destroy path.  Checkout [this section of the Rails routing guide](http://guides.rubyonrails.org/routing.html#singular-resources) to see how you could make a '/logout' url and a logout_path point to a specific controller action. 

It's hard to guess what's going in in your StudentsController without seeing it. BTW if you paste code it can help if you wrap it in ``` so that it is easier to read. See the github flavored markdown at the top of the comment boxes that we're typing in for more formatting options.

**Comment by mitchlloyd** [comment]
@hurtta1 Are you still trying to tackle this problem? If not could you close down this issue?

**Comment by hurtta1** [comment]
I'm still working on trying to fix the problem.

All I keep getting is,

Routing Error
No route matches [DELETE] 

I'm sure there is something simple I am overlooking.  I have all the methods and links for the session modeled off other working components.  

I have a "DELETE     /session/:id(.:format)  session#destroy" listed among all my routs, and Ive tried every variation and possible path name for my`sessions_path(session),method: :delete` call.

**Comment by mitchlloyd** [comment]
It's interesting that you have routes for the singular "session" instead of "sessions". Perhaps you defined the route as a "resource" instead of "resources" in routes.rb? 

In the event that you meant to define a single resource, you should be using session_path without a parameter.

A common way to deal with this sort of thing is to define a custom route like sign_out_path that point to your controllers destroy action. Then you don't need that method: :delete thing.

**Comment by hurtta1** [comment]
I had my route defined as "resources" since that's the way I have everything else.  However, changing it to "resource"  and keeping everything else in there makes it all work... I really have no clue why, but I'll take it.  Thanks for the help.

**Comment by beisert1** [comment]
I am currently having this very same problem except my error is not in StudentsController#edit My error is in StudentsController#index 

here is the error:
![image](https://f.cloud.github.com/assets/6433253/2168806/de59919e-954a-11e3-8ffc-c8544aa925ee.png)

**Comment by beisert1** [comment]
My code should look fairly identical to the assignment 3 repo besides my changes for assignment 4

Let me know if you need to see any of my code, your help is greatly appreciated. My mind has been going in circles for hours trying to figure this assignment out.

My students controller:

```
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.create!(student_params)
    session[:student_id] = @student.id
    redirect_to students_path, notice: "Hi #{@student.name}. Welcome to Bueller!"
  end

  def edit
    @student = current_student
  end

  def update
    current_student.update_attributes!(student_params)
    redirect_to students_path, notice: "Successfully updated your profile"
  end

  def index
    @students = Student.all
  end

  private

  def student_params
    params.require(:student).permit!
  end
end
```

**Comment by beisert1** [comment]
```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id].present?
  end
  helper_method :current_student
end
```

**Comment by beisert1** [comment]
Never mind I fixed it! if anyone else has this problem simply change current_student to current_user in application controller and application layout

**Comment by mitchlloyd** [comment]
What may have happened here is that you logged in (setting the student_id in the session) and then destroyed the student somehow (perhaps dropping the database). Then when you hit the front page, Rails couldn't find the user with the ID listed in your session. 

A short term option would be to clear your browser's cookies to get rid of your session. A better option would be to fix the current_student method to work if the current student has been destroyed. 

Student.find_by(id: sessions[:students_id]) should fix it. This method returns nil if it can't find the student instead of throwing an error.
