### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#53]
After following this guide here: http://railscasts.com/episodes/270-authentication-in-rails-3-1

When I launch my server, I get this following browser error:

![image](https://f.cloud.github.com/assets/6433253/2123194/c7f8dbc0-9226-11e3-8a00-969f27f77ed4.png)

**Comment by Spartan-196** [comment]
As we do not have direct control over our servers you need to ditch the "force_ssl" that guide has you put in place and then clear your cache for the website or at a minimum your cookies. 
Basically if you watch the server process you when you try and hit your page it gives a 304 Page perminately moved and then tries to redirect. However with https not allowed it too tires to redirect back to http and then starts it's loop. I ran into this problem with the same guide.

**Comment by beisert1** [comment]
It works! Thank you @Spartan-196 I never would have figured that out on my own! :+1:
