### ISSUE TITLE
Can't view index for attendances

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#54]
So, I can't get my attendances to display.  I know I have to be missing something simple.  Any ideas?

index.html.erb

```
<h1>Attendances</h1>

<table>
  <tr>
    <th>Seat</th>
    <th>Attended On</th>
  </tr>

  <% @attendances.each do |attendance| %>
    <tr>
      <td><%= attendance.seat %></td>
      <td><%= attendance.attended_on %></td>
    </tr>
  <% end %>
</table>
```

attendances_controller.rb

```
def index
    @attendances = Attendance.all
  end
```

Is there a way for me to tell if I have any attendances in the database at all?  I really am having trouble on finding a way to look at the actual data in the sqlite database.

**Comment by awh112** [comment]
So, the entries are there, but I can't see the seat?

![image](https://f.cloud.github.com/assets/6433265/2155598/b29fe2fe-9448-11e3-9754-b11db9e36d89.png)

I changed my attendances_controller to do this:

```
def create
    @current = current_user

    @attendance = Attendance.new
    @attendance.attended_on = Time.now
    @attendance.seat = params[:seat]
    @attendance.save

    if @attendance.save
      redirect_to attendances_path
    else
      render "new"
    end
  end
```

**Comment by C-Khalid** [comment]
add a debugger after "@attendance.seat = params[:seat]" and see what's the value of @attendance.seat

**Comment by awh112** [comment]
Debugger?

**Comment by C-Khalid** [comment]
yeah, just write  "debugger" in a new line after "@attendance.seat = params[:seat]"

**Comment by awh112** [comment]
Cool!  Let me try and work with this, I'm not quite sure what I'm doing.

**Comment by C-Khalid** [comment]
Then go back to your rails server terminal and type @attendance.seat and it will give the value of @attendance.seat at that point of your code

**Comment by awh112** [comment]
Ok so it was nil.  I was doing this:

```
@attendance = Attendance.new
    @attendance.seat = params[:seat]
    debugger
    @attendance.attended_on = Time.now
    @attendance.student_id = @current.id
    @attendance.save
```

Is params[:seat] not the way to do this?  If I hard code it it works just fine.

**Comment by awh112** [comment]
Here is what I get for the debugger for the params:

![image](https://f.cloud.github.com/assets/6433265/2155796/99153c18-944c-11e3-8ddb-3d3ee06da4bb.png)

**Comment by C-Khalid** [comment]
try params[: attendance][:seat]

**Comment by awh112** [comment]
YES!  That worked!  I had tried everything, params[:attendance].seat, etc.  That did the trick.

Thanks a lot @mekdif.  Now that I know how to use the debugger I think my life is going to be a lot easier...
