### ISSUE TITLE
rspec NoMethodError

### ISSUE THREAD

**Issue by staffordw1** [launchscout/nku#55]
I'm a little confused with what I'm doing wrong with my code. Working through with rspec I discovered that when I get a NoMethodError, I just define a method in the Student.rb file and that generally solves it. But when I got the same error with the other two methods, 'in_seat' and 'absent', just defining those methods didn't change anything, so I don't know if I just defined them wrong or what, but I feel like I they should be going through and giving me some error other than an undefined method error as I'm pretty sure I defined them...

Here's the error:

![error](https://f.cloud.github.com/assets/6433255/2155707/b9b76d08-944a-11e3-8316-a10d4a0318f7.PNG)

And here's my student.rb file:

![code](https://f.cloud.github.com/assets/6433255/2155711/c57e8c3e-944a-11e3-9d03-3855f8649887.PNG)

Any help you guys can give me will be appreciated.

**Comment by jaimerump** [comment]
You don't need to actually define an attendances= to fix that error. You have to define a relationship, `has_many :attendances`, like how we defined a relationship between posts and comments. The other two methods look good other than being empty.

**Comment by staffordw1** [comment]
Well, that fixed it, not sure why exactly but I guess I'll just accept it and move on, thanks!

**Comment by staffordw1** [comment]
So apparently I didn't fix it, it looks like I just created another problem with the missing attribute but I got help with that and managed to fix it, now I'm back to this error which I still don't really know what to do about.

**Comment by staffordw1** [comment]
Yep, I've got no clue, the code looks the same as above but I've changed the attendances= method to just the line has_many :attendances as @jaimerump recommended. The methods are there, that should get me past this error, right?
