### ISSUE TITLE
ActiveModel::MissingAttributeError

### ISSUE THREAD

**Issue by staffordw1** [launchscout/nku#56]
Ok, so the first few errors spec gave me were just NoMethodErrors which were straightforward for the most part, "just define a method". So, I did that, it took me a while to figure out where to define it, but all in all it was fairly simple. Now I'm getting this error:
![screen shot 2014-02-13 at 12 57 55 pm](https://f.cloud.github.com/assets/6433255/2162931/6731c8e2-94d8-11e3-893f-5eade90235a4.png)
 Which is less specific. I've been googling to try to figure out what exactly I'm supposed to do about this, because it's a completely vague error, but a lot of the solutions online for rspec errors have to do with fixing the spec file instead of the code which Isn't helpful in any way. I haven't put anything in my methods yet because I'm not really sure what to put in them just yet. I don't really get it, there should be a student_id defined for every student object. So what exactly does this mean? My code hasn't changed much since my last issue, but here's my Student.rb:

![screen shot 2014-02-13 at 12 53 55 pm](https://f.cloud.github.com/assets/6433255/2162975/d53ab862-94d8-11e3-84dc-7099a45abcd3.png)

 I have nothing written in my attendances controller yet, and my StudentController hasn't changed since the last assignment.

**Comment by staffordw1** [comment]
*StudentsController, it is pluralized

**Comment by swiedaa1** [comment]
Normally I do something silly like forgetting to add to my db. If you go to schema.rb , do you have everything you're calling there? (Before it was name, nickname, email, etc) Personally, I forgot to add seat to mine and I received a bunch of random errors...

**Comment by staffordw1** [comment]
Here's my schema:

![screen shot 2014-02-13 at 1 11 33 pm](https://f.cloud.github.com/assets/6433255/2163077/551ed36e-94da-11e3-8f45-ea830f7b0211.png)

I think everything's there? Do you think I should add another little add_index line that connects attendances to students similar to the line that connects comments to posts?

**Comment by swiedaa1** [comment]
Here is mine: 
`create_table "attendances", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "attended_on"
    t.integer  "seat"
    t.integer  "user_id"
  end`
I'm not sure if much of that matters for you _yet_ because you havent started on the remainder of the project yet but it _could_ be a problem. I've really just been trying things until I get it right. 
If you want to check through my repo to see if it helps you at all, it very well could.
https://github.com/swiedaa1/nku-rails

I also make the mistake of not using plural where plural should be used from time to time. Go through and check all of those? I'm sorry I dont have a perfect answer :(

**Comment by staffordw1** [comment]
One second, it might actually be that I don't have the student_id line in my migration file like you have there... I just have to remember how to add lines to the migration and we'll see if that solves it. Also, I think t.timestamps covers "created_at" and "updated_at" is that right? I forgot to put that in the first time around and so I'll see if I can add that as well real quick.

**Comment by swiedaa1** [comment]
It does, yes, but in the homework ntoes sections they say not to use it:
Note: Although you could use the created_at timestamp to show when students logged their attendance this is not recommended as it will increase the overall difficulty of the assignment, make testing more difficult, and make the code more harder to modify in the future. You should create your own field (attended_on) to log the attendance date.

**Comment by swiedaa1** [comment]
Are you talking about adding to the db?
`def change
  remove_column :users, :password
  remove_column :users, :password_confirmation
 end`
Thats an example. You can use add or remove column. Or were you talking about rake routes? rake db:migrate , etc?

**Comment by staffordw1** [comment]
Yep, looks like that's exactly what I was missing. The add_column thing was what I meant, yeah, I always have to look up how to do that cuz I keep screwing up my database... Anyways, looks like you solved my problem, so thanks!

**Comment by swiedaa1** [comment]
Woohoo! Glad to be of help :)
I run in to the same issues over and over and over again. I literally check through a few of the first issues on Github because there were some awesome answers back there that have really stayed relevant.
