### ISSUE TITLE
Quick question about rspec

### ISSUE THREAD

**Issue by staffordw1** [launchscout/nku#57]
So, I'm a little confused with this last assignment. Looking over the homework notes page, I think I've been trying to do it wrong and that's why I'm so confused. Are we supposed to be using rspec for the bonus assignment only?  Just the query part? If so, then I should probably deal with that only after I've finished writing the code for the assignment and I would do that like we've been doing, is that right? If this is the case then that's my bad for not reading the assignment correctly I suppose, I thought that since we started doing this in class that we were just getting ready to start the next assignment and that would be what we were using to do it from now on, idk that's just the impression I got and I didn't really think too much about it... I guess it's possible I'm the only one that thought that which would be pretty embarrassing...

**Comment by staffordw1** [comment]
Also, sorry for opening so many issues lately...

**Comment by jaimerump** [comment]
I think they just had us using rspec to demonstrate the process of test-driven development, for the people that missed it before. And if we can get our tests passing, that's a bonus point. I get the impression that we're not going to be using rspec too much more in the near future. Maybe toward the end of the semester, but for now I think they're focusing on Rails and ruby.

**Comment by staffordw1** [comment]
Ok, everything makes sense now. I'm an idiot. I've been sitting here trying to do this all week and getting absolutely nowhere and I was wondering why more people weren't opening issues. Now I know what to do, so hopefully I can just knock this out tonight. Thanks!

**Comment by mitchlloyd** [comment]
Thanks for opening an issue about this one. The original plan was to complete the rspec, TDD exercise in class and then use that to complete the next assignment. However, we wanted to slow the pace a little bit and I don't think anyone was able to complete the exercise in class. The assignment for next week will use the solution derived from the rspec exercise. 

Getting your spec to pass isn't required to get the current assignment working or to get 15/15 on the current assignment. I would definitely complete the assignment before attempting to get the spec to pass.

**Comment by jaimerump** [comment]
Just as a note about the rspec part, I found the collect function to be very useful for the in_seat and absent methods.

http://apidock.com/ruby/Array/collect
