### ISSUE TITLE
Error saving seat number for attendance

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#58]
![image](https://f.cloud.github.com/assets/6433253/2168928/e7114f3a-954e-11e3-9092-d571af167403.png)

```
class AttendancesController < ApplicationController
  def new
    @attendance = Attendance.new
  end

  def create
    @current = current_user

    @attendance = Attendance.new
    @attendance.seat = params[:attendance][:seat]
    @attendance.attended_on = Time.now
    @attendance.student_id = @current.id
    @attendance.save

    if @attendance.save
      redirect_to attendances_path, :notice => "You have successfully logged your attendance."
    else
      render "new"
    end
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def index
    @attendances = Attendance.all
  end
end
```

**Comment by mitchlloyd** [comment]
Looks like your current_user is nil. Are you signed in?

**Comment by beisert1** [comment]
Seems like your right, after I sign in it doesnt show the sign out button anymore or the hi @username with edit your profile anymore either:

![image](https://f.cloud.github.com/assets/6433253/2173142/5f61719c-959d-11e3-8a80-758b26a61a56.png)

Seems like thats the problem but im not sure how that got changed?

**Comment by beisert1** [comment]
fixed it! Had to do with my problem earlier from dropping the database!
