### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by w1ll1am23** [launchscout/nku#6]
Not sure what I am doing wrong. I have looked over everything three times. Anyone have any ideas?

![screenshot - 01212014 - 06 58 01 pm](https://f.cloud.github.com/assets/6432770/1969745/16146a10-82f8-11e3-8bf3-93ac27a3f4a8.png)

**Comment by stewartt4** [comment]
I remember coming into an error like this, but it was because I defined 'new' in my posts controller under a private method, so then the view could not access my @post variable. I'm not sure if this is the same situation but it's worth a look.

**Comment by jaimerump** [comment]
I doubt that's the case, the error is occurring in the show action. @w1ll1am23 I would check the show action in your controller, you might be missing something in it that's causing that to be undefined.

**Comment by w1ll1am23** [comment]
I had my private method post_params in the middle of my controller and had the  show and index below that. The post controller couldn't access the variable. All is good now. Thanks for the help guys.
