### ISSUE TITLE
Student index page

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#63]
What should our student index page look like at this point?  Do we just want our grid of in class students and our list of absent students, without the previous list that we had of all the students?  If so, how should students edit their records since that was part of the original grid?

**Comment by swiedaa1** [comment]
Sort of in addition to this question, will we have the demo app up and running? I personally thought it helped a little bit in giving us an idea as to where to go.

I used a table on the attendance page, rather than the "home page" that displayed the image,name, email, etc. I felt like we may need that page later on. Doing this on the attendance page also allowed to keep the edit/delete options as well.

**Comment by rockwood** [comment]
Sorry guys, it looks like we didn't push the right thing to heroku. It's up there now.

http://nku-rails.herokuapp.com/

**Comment by staffordw1** [comment]
How close to that do we want it? I've been doing pretty much the bare minimum so far and haven't messed around with any CSS at all. My table shows up like this:

![screen shot 2014-02-20 at 5 16 14 pm](https://f.cloud.github.com/assets/6433255/2224266/ab311210-9a7c-11e3-8da5-82fd2ab60b16.png)

Does it have to be a 2x2 grid or is this good enough?

**Comment by staffordw1** [comment]
Well, I guess the assignment says that it should be a grid, so I guess I'll just go ahead and do that...

**Comment by awh112** [comment]
I kind of did mine like a grid, except I used background color to distinguish rather than a thick border.

**Comment by Spartan-196** [comment]
i just set up bootstrap-sass and messed with the styling for my tables as they are displaying a in a 2x2 table with a footer row. Though after installing sass i borked my sign out somehow

**Comment by awh112** [comment]
Were you able to get them to display underneath each other?  Best I could do was side by side.

**Comment by Spartan-196** [comment]
Mine is done using the skeleton below example pages posted on herokuapp

```
<table>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
  </tr>
  <tfoot>
    <tr>
      <td colspan=2 align=center>Front Of Class Room</td>
    </tr>
  </tfoot>
</table>
```
