### ISSUE TITLE
Logout issue after adding bootstrap-sass

### ISSUE THREAD

**Issue by Spartan-196** [launchscout/nku#65]
I added the bootstrap-sass gem as well as the rails_layout gem and then generated my layouts which auto created the additional empty css sheets as well as the default one. However now then a user tries to sign out I get a very generic message of "The action 'show' could not be found for SessionsController" though there is and never was a show action in it
Nor is my logout function calling anything called 'show'. 

Has anyone gotten bootstrap-sass working? or tried to?

**Comment by rockwood** [comment]
Installing bootstrap shouldn't have any affect on your sessions controller. Without seeing any code it's hard to diagnose the problem. What route are you hitting? What does your sessions controller look like?

**Comment by Spartan-196** [comment]
All of my code is available at https://github.com/Spartan-196/nku-rails 
Through the use of screen I have made my server always up at http://atkinsonj3-72805.use1.nitrousbox.com/ 

As far as I can see I am not getting route problems out problems.
There is no show defined in my sessions controller

```
class SessionsController < ApplicationController

def create
  student = Student.find_by_email(params[:email])
  if student && student.authenticate(params[:password])
    session[:student_id] = student.id #if user is authenticated set session id to user id
    redirect_to students_path(student.name), :notice => "Logged in!" #redirect to main student page with notice of successful login
  else
    flash[:error] = "Invalid email or password" #if auth. fails, vaguely specify that they failed the login 
    redirect_to sessions_path
  end
end

  def destroy
    session[:student_id] = nil #nullify currently set session ID 
    redirect_to students_path, :notice => "Logged out!" #redirect with notice
  end
end
```

This is where my sign in signout code is

```
<% @current = current_student %> <!--Find current user login-->
<% if @current == nil %> <!-- if no login show new secctions with sign up/sign in links {will edit later to look nice}-->
      <div class="nav" allign=right><%= link_to 'Sign up', new_student_path %> <strong>|</strong> <%= link_to 'Sign in', sessions_path %>
        <% else %>
        <h3>Welcome,</h3> <%= current_student.name %> | <%= link_to "Sign out", session_path(session), method: :delete, data: { confirm: 'Are you sure you want to sign out?' } %>
        <%= link_to 'I\'m Here', new_attendance_path %>
        <% end %>
        </div>
```

I am not directing it to any thing 'show' related, that should only be next to the user profiles to see them on their own pages which does still work.

**Comment by Spartan-196** [comment]
hard reverted having found out that the javascript :delete relies on got jacked after what i think was the install off rails_layout gem in combination with bootstrap-sass. Starting over on some stuff
