### ISSUE TITLE
Clear attendances table?

### ISSUE THREAD

**Issue by beisert1** [launchscout/nku#67]
I have filled this table and cant see any new entries anymore. Is there an easy and safe way to clear this table, I dont want to go through the headache of migration errors that ive had before.

![image](https://f.cloud.github.com/assets/6433253/2230973/50954ce8-9b0a-11e3-95cc-68c107007591.png)

**Comment by rockwood** [comment]
you can do the following from the console:

```
rails console
Attendance.destroy_all
```

**Comment by beisert1** [comment]
Thank you that worked perfectly
