### ISSUE TITLE
More info being displayed than I want

### ISSUE THREAD

**Issue by Sidebottom1** [launchscout/nku#69]
I've tried several different approaches to do this, and all of them end up with this same type of result.  Note that I did all I could to try to find the root of the problem first before just trying to change it and hope it fixed itself, and it seems like the root of the problem is right there in the index.html.erb (in user).  I've got no clue here, I'll go ahead and push what I have so anyone who wants to help can see my code is able to do so.
![why](https://f.cloud.github.com/assets/6433234/2236319/6a2924ae-9b5a-11e3-9425-d8c3386c6c98.jpg)

**Comment by Sparkesg1** [comment]
```
<%= User.in_seat(1).each do |s1| %>
```

should be 

```
<% User.in_seat(1).each do |s1| %>
```

It is showing an = in all of them so remove that from each one.

**Comment by Sidebottom1** [comment]
........5 equals signs gave me 2 hours of headache.   Thanks spark, I think I tried just about everything possible but looking at one of the most obvious things possible.
