### ISSUE TITLE
Tutorial - 5.6: Saving data in the controller

### ISSUE THREAD

**Issue by MatthewMcElwain** [launchscout/nku#7]
I keep getting this error and I'm not sure what to do.

![capture 2](https://f.cloud.github.com/assets/6433263/1969763/a67317aa-82f8-11e3-9a42-84c3d553af87.JPG)

I followed the tutorial as best as I could so I figure it might be the way the code is arranged in posts_controller.rb

**Comment by jaimerump** [comment]
When does this error occur? When you navigate to /posts/new? When you
submit the form to create a new post?

On Tue, Jan 21, 2014 at 7:10 PM, MatthewMcElwain
notifications@github.comwrote:

> I keep getting this error and I'm not sure what to do.
> 
> [image: capture 2]https://f.cloud.github.com/assets/6433263/1969763/a67317aa-82f8-11e3-9a42-84c3d553af87.JPG
> 
> I followed the tutorial as best as I could so I figure it might be the way
> the code is arranged in posts_controller.rb
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaslight/nku/issues/7
> .

## 

Jaime Rump
Trengine
Voice_ +1/859.907.4305
eMail_ jaime.rump(at)trengine.com

**Comment by jaimerump** [comment]
I don't think the placement of the code should matter, Rails should be smart enough to figure out that that's a set of rules to validate posts by when you submit the form.

**Comment by mitchlloyd** [comment]
This error is saying that your `params` doesn't contain attributes for `post`. This probably has something to do with how you have your form setup in your view. You can see in the error that your form sent no parameters.

Check your form work from 5.2 and see if that helps.

**Comment by MatthewMcElwain** [comment]
It works now, I just made an observation error. I put code in the new controller when it was supposed to go in the create controller
