### ISSUE TITLE
Is anyone else getting tomorrow's date when using Date.today?

### ISSUE THREAD

**Issue by daileyj8** [launchscout/nku#70]
i went into rails console and looked at Date.today, and it even said it was tomorrow from command line. I was just wondering if anyone else was getting this

**Comment by Sparkesg1** [comment]
Yes, it deals with the time of the servers being a different time than we are at.  It changed over at 7pm according to mine.

**Comment by jaimerump** [comment]
That's strange, the boxes show up as US East, but it sounds like they're running GMT. @rockwood @mitchlloyd, do we have the access necessary to change the time zone on our boxes, or is this just something we have to be aware of when doing evening testing?

**Comment by cdmwebs** [comment]
You don't have to change it for the whole box, just your app. Check out the [guide](http://guides.rubyonrails.org/configuring.html#rails-general-configuration) and the [docs](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html).

Tip: `rake time:zones:us` will probably be helpful, too.
