### ISSUE TITLE
Date inputs

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#72]
How the heck do you have a date input and grab the date and use it without saving it to the model?

There should be a way, I'm just missing it...

**Comment by jaimerump** [comment]
If you put it in the url with a get request, then in the controller you can access it with `params[:date]` or whatever you named the field.

**Comment by awh112** [comment]
And how exactly should we be putting that in the URL with a get request?  I think I might be a little lost...I know we did it with students.

**Comment by awh112** [comment]
I'm not having much luck refreshing the page with added params.  I am doing something like this:

```
<div>Date to display: <input type="date" name="date_field" value=<%= Date.today %>>
  <%= link_to "Refresh", refresh_path(:test => "test"), class: "btn btn-default navbar-btn"%>  
```

Should I be doing something in the controller?

**Comment by staffordw1** [comment]
In the students_index view, just use a form_tag specifying the students path (which should redirect you back to the same page your already on) but add 'get' as the method. Then get the date entered and pass it as a param back to the student's path when the submit button is clicked, that way you can simply call it using params[:attended_on] or whatever you called it.

**Comment by staffordw1** [comment]
You don't need to do anything with the controller

**Comment by awh112** [comment]
So, I would have this:

```
<%= link_to "Refresh", students_path, class: "btn btn-default navbar-btn"%>  
```

but how would I specify it as a 'get'?

**Comment by awh112** [comment]
I see I have this route:

```
attendances GET    /attendances(.:format)          attendances#index  
```

**Comment by awh112** [comment]
That and I can't even manage to get the value of the control, either.

**Comment by staffordw1** [comment]
I think that would work also, as long as you have the form_tag and it's doing a get request and your passing the input back to the same page. 

I believe you don't need to reference your Attendances model or any paths associated with it at all because of the Student has many attendances relationship, Just querying students for their attended_on values should work.

**Comment by awh112** [comment]
But how can I get at that input value?  I've tried everything.  My input being:

```
<input type="date" name="date_selected" value=<%= params[:foo] %>
```

**Comment by awh112** [comment]
Even things like date_selected.value don't seem to work like you'd think they would.

**Comment by camdixon** [comment]
You need to do it at the start of your `form_tag` just like staffordw1 mentioned.  You can specify a get request like this.
`<%= form_tag students_path, method: :get do %>`
This form_tag is used as the start of the date picker.

**Comment by staffordw1** [comment]
I', just making pretty wild assumptions based on my own personal experiences cause I have no experience with this stuff either before this class so don't hate me if I get some stuff wrong here but I think name is just what will appear in the url after the refresh. It should say something like &commit=date_selected up there and that's pretty much all that is I think.

Not sure how you would do it that way honestly... The way I did was with this

```
<%= label_tag :attended_on %>
<%= date_field_tag :attended_on, params[:attended_on] %>
```

and that's all with a form tag. Then I have a submit tag just called search and I assign nil to the name value so that that commit= doesn't appear at all in the url.

**Comment by staffordw1** [comment]
Sorry that was in reply to awh, yes I did it the same way as camdixon is saying

**Comment by awh112** [comment]
So, I should have a `form_tag` in my index page?

**Comment by staffordw1** [comment]
Yep, that seems to be the solution, I wasn't sure if there was a way to do it other wise with the redirect_to and whatnot so I didn't say it outright but yeah a form_tag will totally work

**Comment by camdixon** [comment]
Yes, because it's a date picker form, and we use the _tag because of the date picker I believe.  We specify the `:get` because we don't want it submitting anything back to the server.
That's my understanding of why we are using it based on what Kevin said in class last week.

**Comment by awh112** [comment]
So here is my relevant code:

```
<%= form_tag students_path, method: :get do %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% @current = current_user %>

<%if params[:selected_date] == nil %>
<%  params[:selected_date] = Date.today %>
<% end %>

<style>
  h4 {display: inline}
  .seats1 {background: lightgray; padding: 10px; width: 400px}
  .seats2 {background: gray; padding: 10px; width: 400px}
  .in-class {border-spacing: 8px;}
</style>

<h1>Students</h1>
<% debugger %>
<div>Date to display: <%= date_field_tag :selected_date, params[:selected_date] %>
  <%= link_to "Refresh", students_path, class: "btn btn-default navbar-btn"%>  
  <%= link_to "View all attendances", attendances_path, class: "btn btn-primary navbar-btn"%>
</div>
```

Still doesn't like my refresh.  What am I doing wrong?

**Comment by awh112** [comment]
Ok, so the problem was I was not using a submit_tag, but a link_to.

Thank you @camdixon and @staffordw1 for all of your help!
