### ISSUE TITLE
I can get the sign in to work

### ISSUE THREAD

**Issue by alexkoepke** [launchscout/nku#73]
Link to app: http://sheltered-depths-6033.herokuapp.com/students

https://github.com/alexkoepke/nku-rails/tree/new-nku-rails

https://github.com/alexkoepke/nku-rails/blob/new-nku-rails/app/controllers/sessions_controller.rb

https://github.com/alexkoepke/nku-rails/blob/new-nku-rails/app/views/sessions/new.html.erb

https://github.com/alexkoepke/nku-rails/blob/new-nku-rails/config/routes.rb

**Comment by staffordw1** [comment]
What's the error you're getting? Or is it just not working?

**Comment by alexkoepke** [comment]
When I click sign in it says the sign in info is incorrect.

The first link is a like to my app. My server is currently running.
—
Alex Koepke
(513) 236-7281

**Comment by alexkoepke** [comment]
Had to shut my server down I will start it back up when I get home. All my changes have been pushed to GitHub.

**Comment by alexkoepke** [comment]
Its back up. you can also view my app here http://sheltered-depths-6033.herokuapp.com/students

**Comment by alexkoepke** [comment]
I needed to add [:sessions] in front of [:email] and [:password].

thanks for your help Jaime R.
