### ISSUE TITLE
Changing server time zone

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#76]
I am trying to run this command, but am told I don't have sudo privileges:

```
sudo dpkg-reconfigure tzdata
```

Is this the right way to do this?

**Comment by jaimerump** [comment]
You should just be able to change the time zone in application.rb

**Comment by awh112** [comment]
Doesn't seem to work, mine looks like this:

```
config.time_zone = 'Eastern Time (US & Canada)'
```

**Comment by swiedaa1** [comment]
Try using 
`Time.zone.now` or `Time.zone.today`
instead of 
`Time.now`.

**Comment by awh112** [comment]
That doesn't quite get it...I am using the Date class.  Also, does that affect the server settings at all?  If we are configuring the server to run eastern time, does the application.rb affect it?

**Comment by awh112** [comment]
I'm pretty convinced this can't be done without root access... @mitchlloyd, @rockwood, am I going about this the right way?

Also, I don't know if mentioning someone in github like that notifies them, but I hope so...

**Comment by awh112** [comment]
Also, @swiedaa1, I think you actually were right.  I can use the Time.zone.now, since that is what is configured in the application.rb file.  However, what I am wondering now is if that is sufficient for this assignment.

**Comment by mitchlloyd** [comment]
What @jaimerump is saying is what I believe. The change in application.rb should do it.  Server admin with sudo should not be required.
