### ISSUE TITLE
Student index

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#77]
So, if we are using our student index for our seating chart, what is the best way to approach adding a student index page that just shows student information?

**Comment by beisert1** [comment]
Kevin and Mitch's version may help: http://nku-rails.herokuapp.com/ 

Seems to be just a separate page with the seating chart and date stripped out.

**Comment by awh112** [comment]
Thanks.  I actually ended up using a parameter and changing my view based on the params passed in the query.  Not sure if it is better/worse.
