### ISSUE TITLE
ActiveRecord question

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#80]
So, in trying to filter the assignments, I ran into an issue where my view kept complaining that the 'each' method was not defined when I was trying to do this:

```
<% @assignments.each do |assignment| %>
```

In my controller, I was doing this:

```
@assignments = Assignment.find_by_student_id(params[:id])
```

and it didn't work.  However, when I changed it to this, I got what I needed (an ActiveRecord relation returned):

```
@assignments = Assignment.where("student_id = ?", params[:id])
```

My question is, why?  It doesn't make sense why the find_by wouldn't return an ActiveRecord::Relation object.

**Comment by jaimerump** [comment]
If find_by_student_id didn't return an ActiveRecord::Relation, what did it return?

**Comment by mitchlloyd** [comment]
The rails `find` methods always return one record.  So

``` ruby
  Assignment.find_by_student_id(params[:id])
```

Is equivalent to

``` ruby
  Assignment.where("student_id = ?", params[:id]).first # or limit(1) in more SQL terms.
```

Also just as a note, it might be even simpler to do

``` ruby
  Student.find(params[:id]).assignments
```

I just figured you're probably in a StudentsController so you might have already found a student.
