### ISSUE TITLE
Adding upload action?

### ISSUE THREAD

**Issue by awh112** [launchscout/nku#84]
I read in the documentation that we need to add this to our forms to use the upload properly:

```
<%= form_tag({action: :upload}, multipart: true) do %>
```

but I'm confused on the proper syntax when other properties are defined.  I currently have it like this and it isn't breaking:

```
<%= form_tag assignments_path, method: :get, action: :upload, multipart: true do %>
```

Is that right?  On my upload click, I don't seem to be hitting the defined upload in the controller:

```
<h3>Or upload a .csv list of assignments:</h3>
<%= file_field_tag 'upload_file' %>
<br/>
<%= submit_tag("Upload", class: "btn btn-primary navbar-btn") %>
```

**Comment by awh112** [comment]
I seem to be getting this error a lot:

![image](https://f.cloud.github.com/assets/6433265/2507492/0a518d56-b3be-11e3-9be1-4153b5e1a8cb.png)

**Comment by mitchlloyd** [comment]
It looks like you're  on the right track, but here are some pointers:
- In your routes it would be more conventional to have resources uploads.
- Controller names should always be pluralized.
- If you have an UploadsController the action "upload" is redundant. You would conventionally use the "create" action (post to /uploads)
- Make sure your form is using the right Http verb (method). It looks like you set it to get when it should be a post (the default).

**Comment by awh112** [comment]
So, for whatever reason, it worked when I changed it from upload to create.  Not sure why, but that is what fixed it for me.  Thanks, @mitchlloyd.
