### ISSUE TITLE
SASS Error

### ISSUE THREAD

**Issue by camdixon** [launchscout/nku#87]
I'm not really sure where to start, but I have this error on my page when the app loads.  I don't really understand where this is coming from as my view code seems to be fine, and it should load the style sheet.  
![selection_010](https://cloud.githubusercontent.com/assets/4430359/2584043/57c2e60e-b9d9-11e3-85e9-97cb029330fe.png)

Here is my sass code 

```
.first-col
  border-left: 1px solid #bbb

.col-sm-1
  padding-left: 5px
  padding-right: 5px
  border-right: 1px solid #bbb

.first-row
  border-top: solid 1px #bbb

.row-time
  @extend .row
  height: 60px
  border-top: solid 1px #bbb

.last-row
  @extend .row-time
  border-bottom: solid 1px #bbb

.element-height
  height: 100%

.avatar
  height: 150px
  width: 150px
  overflow: hidden
  background-repeat: no-repeat
  background-size: contain

.info-block
  display: block
  float: left
  margin-left: 20px

.list-item
  @extend .clearfix
  margin-bottom: 20px

.push--top
  margin-top: 20px

.border-dark
  border: solid 2px black

.offset-color
  background-color: #D6E6FF

#footer
  height: 110px
```

**Comment by camdixon** [comment]
Specifically this line of code in my view breaks my app.
It is when I include the SASS file.

```
<%= stylesheet_link_tag    "application", media: "all" %>
```

Also, it is the same link that is used in the base nku-project repository.
I ran bundle & bundle install and also the bootstrap gem is in the gemfile.

**Comment by camdixon** [comment]
The issue has been fixed by renaming the application.scss file from the base repository 'nku-project' to 

```
application.sass
```

Not sure why this worked or is needed.

**Comment by mitchlloyd** [comment]
You need to add a semicolon after the following in your `application.scss` file like this:

```
import @bootstrap;
```

That is a mistake in the template nku-project template.

**Comment by camdixon** [comment]
Should I rename the file back to application.scss and add the semi-colon instead of my solution?

**Comment by mitchlloyd** [comment]
@rockwood and I usually use the .sass syntax, because it's a little less noisy, but I believe the thought was that the scss syntax might be better for the class because it looks a lot more like normal css. Feel free to use sass syntax that you're using.
