### ISSUE TITLE
Site won't collapse on mobile

### ISSUE THREAD

**Issue by alexkoepke** [launchscout/nku#90]
Here is my app, http://sheltered-beach-2844.herokuapp.com/, the site will collapse if you change your desktops browser window. However, if you open it on your phone it will not collapse.

/app/assets/javascripts/application.js

```
//= require jquery
//= require jquery_ujs
//= require bootstrap
//= require_tree .
```

/app/assets/stylesheets/application.scss

```
@import 'bootstrap'
```

https://github.com/alexkoepke/nku-project

**Comment by cdmwebs** [comment]
Add this to the head of your application layout:

<meta name="viewport" content="width=device-width, initial-scale=1">
—

**Comment by alexkoepke** [comment]
Hell yeah! Thanks!
