### ISSUE TITLE
I'm thinking about using devise

### ISSUE THREAD

**Issue by alexkoepke** [launchscout/nku#91]
https://github.com/plataformatec/devise

My questions are. 
- Has anyone used it before? 
  - If so could you share your experience.
- When does this become to late to implement?
- Do I need other things to implement it?

**Comment by mitchlloyd** [comment]
Devise is really popular and well documented so it should be easy to implement. For most web applications, managing sessions and password resets isn't an important or interesting part of the domain, making authentication a reasonable feature to implement with a library.

**Comment by alexkoepke** [comment]
Can I add it to my app or should it be a first step?—
Alex Koepke
(513) 236-7281

**Comment by mitchlloyd** [comment]
You can definitely add it to your app. You'll have to figure out what
database fields it needs to have on the user model. You can probably do
that by just running through the install process with a dummy user model
and seeing what it spits out in schema.rb.

**Comment by alexkoepke** [comment]
Thank you! I will try that.—
Alex Koepke
(513) 236-7281
