### ISSUE TITLE
Who wants an invite to prelang?

### ISSUE THREAD

**Issue by alexkoepke** [launchscout/nku#92]
Leave your email here if you would like an invite to prelang.

You can check out what prelang is here.
http://prelang.com/

**Comment by Spartan-196** [comment]
I have already signed up for their invite emails. 
Are you saying you have invite codes to send?

**Comment by alexkoepke** [comment]
Yup! All I need is your email and I'll send you an invite.

**Comment by staffordw1** [comment]
Well, if that's the case I'd like one as well, please:

staffordw1@nku.edu

I've already signed up as well but haven't received the invite yet...

**Comment by swiedaa1** [comment]
Well uh, I could use this.

swiedaa1@nku.edu

**Comment by Spartan-196** [comment]
I guess I'll take one as well. 
atkinsonj3@nku.edu

**Comment by alexkoepke** [comment]
Your invite to staffordw1@nku.edu has been sent!

**Comment by alexkoepke** [comment]
Your invite to atkinsonj3@nku.edu has been sent!

**Comment by staffordw1** [comment]
Thanks, man!

**Comment by alexkoepke** [comment]
No problem!—
Alex Koepke
(513) 236-7281

**Comment by hopscotchscooter** [comment]
I'll take an invite and see what it's all about if you still got some. E-mail is lewickid1@nku.edu

**Comment by alexkoepke** [comment]
Your invite to lewickid1@nku.edu has been sent!

**Comment by hopscotchscooter** [comment]
Thanks @alexkoepke !

**Comment by mikemoll** [comment]
mike.g.moll@gmail.com
Thanks 
i'm building a Job's Board for An NGOs In east africa prelang will help tremendously

**Comment by alexkoepke** [comment]
Do you have another email that I could use to send you the invite? It says
the email mike.g.moll@gmail.com has already been taken. I'm guessing its
because you signed up with that email to receive further information.

**Comment by mikemoll** [comment]
Thanks I got an invite. 
Thanks a lot. 

Mike.

**Comment by alexkoepke** [comment]
No problem! Glad I could help!
