### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by hurtta1** [launchscout/nku#95]
I've been trying to figure this out for several days now, I've come across a dozen or so causes for it online and none of which help...  Every page on my site is completely blank, the only thing that shows up is my navbar.  I get no errors, no issues at all, just blank pages.  Nothing I put onto any view shows up.  The page elements show nothing except the navbar and even when that code isn't present nothing appears on the page.  Operational links go to the right paths, but nothing gets rendered.. I have no clue what is wrong.

**Comment by Spartan-196** [comment]
you need to add the yield information for rending your pages back into your layout template page app/views/layouts/application.html.erb 

Stick this under your navigation links.

```
<div class="container">
  <%= yield %>
</div>
```

at the very least keep the `<%= yield %>`

**Comment by hopscotchscooter** [comment]
@Spartan-196 is correct. That's what worked for me when I had the issue several weeks ago.

**Comment by camdixon** [comment]
Why does the yield command work?  Why would it not work without it?  Just curious.

**Comment by Spartan-196** [comment]
To the best of my knowledge it is in the layouts view by default and tells rails where it needs to put the rest of the content from the views. The [rails guide](http://guides.rubyonrails.org/layouts_and_rendering.html#understanding-yield) has very short section about it.

**Comment by hurtta1** [comment]
Yea that did it, thanks for the help everybody.
