### ISSUE TITLE
validation errors

### ISSUE THREAD

**Issue by hurtta1** [launchscout/nku#98]
I can't quite figure out why this isn't working since I've had a similar setup before.  When I create a new user my model is supposed to validate a few fields, and it does.. However, instead of listing the errors on the creation page like it should, I get one of these pages.
![image](https://cloud.githubusercontent.com/assets/6433250/2820413/cadf5da4-cef9-11e3-9299-fe3fc34dde0c.png)

i have this in my model 

``` ruby
  validates_presence_of :name, :number, :age, :on => :create
```

and this in my creation form 

``` ruby
<%= form_for @player do |f| %>
  <% if @player.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@player.errors.count, "error") %> Please check your submission:</h2>
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
```

I've checked out some tutorials and examples and pretty much everything is exactly the same, I'm not sure what I'm missing.  Any ideas would be appreciated

**Comment by jaimerump** [comment]
The line that's highlighted is `create!` From what I've seen, the exclamation mark usually gives you an error page like that instead of failing normally.

**Comment by hurtta1** [comment]
hmm, well that certainly changed it.. except now I get:

Template is missing
Missing template players/create, application/create with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :raw, :ruby]}. Searched in: \* "/home/action/nku-project/app/views" 

That one I have not seen before. I do have a create method in my controller.

**Comment by jaimerump** [comment]
It looks like you don't have an else on that if block. If it saves correctly, it redirects, but if it doesn't save correctly, it doesn't have anything to do so it tries to render create.html.

**Comment by hurtta1** [comment]
Yea I kind of thought that, but all of the examples I've see have almost that exact same block for the form.
